# PDX Analysis Tutorial - Environment Setup
# Conda environment specification
# Create environment with: conda env create -f environment.yml

name: pdx_analysis
channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  # Python runtime
  - python=3.9

  # Core data science
  - pandas>=1.3.0
  - numpy>=1.20.0
  - scipy>=1.7.0
  - matplotlib>=3.4.0
  - seaborn>=0.11.0
  - scikit-learn>=1.0.0
  - statsmodels>=0.12.0

  # Jupyter environment
  - jupyter
  - ipython
  - ipykernel
  - jupyterlab

  # Plotting
  - plotly>=5.0.0

  # R and R packages
  - r-base=4.3
  - r-ggplot2
  - r-dplyr
  - r-tidyr
  - r-readr
  - r-lme4
  - r-broom
  - r-scales
  - r-rcolorbrewer
  - r-gridextra
  - r-knitr
  - r-rmarkdown
  - r-testthat
  - r-devtools
  - r-car
  - r-survival

  # Development tools
  - black
  - flake8
  - pytest
  - pytest-cov

  # System tools
  - git
  - curl
  - wget

  # Additional Python packages via pip
  - pip
  - pip:
    - loguru>=0.5.0
    - faker>=13.0.0
    - configparser>=5.0.0
    - tqdm>=4.62.0
    - sphinx>=4.0.0
    - sphinx-rtd-theme>=0.5.0